# Generated by Django 5.0.6 on 2024-06-19 19:40

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip_code_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(max_length=10, verbose_name='ZIP Code'),
        ),
    ]
